const products = [
  {
    id: "001",
    image: "/assets/1.png",
    productName: "Blouse and belted skirt",
    gene: "Female",
    age: "Ranges",
    price: "N 8,900.00",
  },
  {
    id: "002",
    image: "/assets/2.png",
    productName: "Pink ankara mixed gown",
    gene: "Female",
    age: "0 - 11",
    price: "N 8,900.00",
  },
  {
    id: "003",
    image: "/assets/3.png",
    productName: "A - shaped gown",
    gene: "Female",
    agege: "Ranges",
    price: "N 8,900.00",
  },
  {
    id: "004",
    image: "/assets/4.png",
    productName: "Blouse and belted skirt",
    gene: "Female",
    age: "Ranges",
    price: "N 8,900.00",
  },
  {
    id: "005",
    image: "/assets/5.png",
    productName: "Ankara suit",
    gene: "Male",
    age: "Ranges",
    price: "N 8,900.00",
  },
  {
    id: "006",
    image: "/assets/6.png",
    productName: "Browm ball gown",
    gene: "Female",
    age: "0 - 11",
    price: "N 8,900.00",
  },
  {
    id: "007",
    image: "/assets/7.png",
    productName: "Male suit",
    gene: "Male",
    age: "Ranges",
    price: "N 8,900.00",
  },
  {
    id: "008",
    image: "/assets/8.png",
    productName: "Flared gown",
    gene: "Female",
    age: "Ranges",
    price: "N 8,900.00",
  },
];
